apiVersion: v1
kind: Pod
metadata:
  name: pod-ConfigMap
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: course
        valueFrom:
          configMapRefKey:
            name: daws78s
            key: cource
      - name: trainer
        valueFrom:
          configMapRefKey:
            name: daws78s
            key: trainer